const Map<String, String> arTranslations = {
  // General
  'app_title': 'تطبيق أوتولاب للطلاب',
  'ok': 'حسناً',
  'cancel': 'إلغاء',
  'error': 'خطأ',
  'success': 'نجح',
  'loading': 'جاري التحميل...',
  'no_data': 'لا توجد بيانات',
  'retry': 'إعادة المحاولة',

  // Roles / labels
  'student': 'طالب',
  'role_student': 'طالب',

  // Auth
  'login': 'تسجيل الدخول',
  'register': 'إنشاء حساب',
  'email': 'البريد الإلكتروني',
  'password': 'كلمة المرور',
  'name': 'الاسم',
  'logout': 'تسجيل الخروج',
  'app_subtitle_students': 'بوابة الطالب للمعامل والجلسات والدرجات',
  'sign_in_title': 'تسجيل الدخول',
  'sign_in_subtitle': 'الوصول إلى المعامل والجلسات والتقدم الدراسي',
  'email_required': 'البريد الإلكتروني مطلوب',
  'email_invalid': 'يرجى إدخال بريد إلكتروني صالح',
  'password_required': 'كلمة المرور مطلوبة',
  'password_too_short': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
  'forgot_password': 'هل نسيت كلمة المرور؟',
  'no_account_register': 'ليس لديك حساب؟ أنشئ حساباً',
  'register_subtitle_students': 'انضم إلى الدورات والمعامل في أوتولاب',
  'create_account_title': 'إنشاء حساب',
  'create_account_subtitle': 'سجل كطالب للوصول إلى معاملك',
  'name_required': 'الاسم مطلوب',
  'already_have_account_login': 'لديك حساب بالفعل؟ سجّل الدخول',
  'confirm_password': 'تأكيد كلمة المرور',
  'password_mismatch': 'كلمتا المرور غير متطابقتين',

  // Home
  'home_dashboard': 'الصفحة الرئيسية',
  'home': 'الرئيسية',
  'my_labs': 'معاملي',
  'sessions': 'الجلسات',
  'attendance': 'الحضور',
  'grades': 'الدرجات',
  'files': 'الملفات',
  'chat': 'المحادثة',
  'complaints': 'الشكاوى',
  'settings': 'الإعدادات',
  'see_all': 'عرض الكل',
  'greeting_generic': 'مرحباً بعودتك',
  'today_overview': 'اليوم',
  'today_overview_subtitle': 'اطّلع على الجلسات القادمة وآخر الأنشطة',
  'tap_to_open': 'اضغط للفتح',

  // Settings
  'theme': 'السمة',
  'language': 'اللغة',
  'server_ip': 'عنوان الخادم',
  'light': 'فاتح',
  'dark': 'داكن',
  'theme_light': 'سمة فاتحة',
  'theme_dark': 'سمة داكنة',
  'account_section': 'الحساب',
  'app_section': 'التطبيق',
  'about_section': 'حول',
  'profile_details': 'بيانات الملف الشخصي',
  'about_app': 'حول التطبيق',
  'about_app_description':
      'تطبيق أوتولاب للطلاب يساعدك على متابعة المعامل والجلسات والدرجات.',
  'privacy_policy': 'سياسة الخصوصية',
  'logout_title': 'تسجيل الخروج؟',
  'logout_message': 'سيتم تسجيل خروجك من هذا الجهاز.',

  // Streaming
  'watch_live_stream': 'مشاهدة البث المباشر',
  'watching_live_stream_of_session': 'مشاهدة البث المباشر للجلسة',
  'connecting': 'جاري الاتصال...',
  'waiting_for_stream': 'في انتظار بدء البث...',
  'receiving_stream': 'استقبال عرض البث...',
  'stream_connected': 'تم الاتصال بالبث',
  'stream_ended': 'انتهى البث',
  'connection_error': 'خطأ في الاتصال',
  'stream_not_available': 'البث غير متاح',
  'live_stream_placeholder': 'بث مباشر\n(مشغل فيديو تجريبي)',
  'reconnect': 'إعادة الاتصال',

  // Attendance
  'scan_qr': 'مسح رمز QR',
  'show_attendance_qr': 'عرض رمز الحضور',
  'show_attendance_qr_hint':
      'اعرض هذا الرمز لمعلمك عند تسجيل الحضور.',
  'attendance_qr_hint':
      'افتح جلسة واضغط "عرض رمز الحضور" أثناء المحاضرة.',
  'attendance_qr_error': 'تعذر تحميل رمز الحضور',
  'refresh_qr': 'تحديث الرمز',
  'expires_at': 'ينتهي في',
  'attendance_history': 'سجل الحضور',

  // Complaints
  'submit_complaint': 'إرسال شكوى',
  'my_complaints': 'شكاواي',
  'submit_or_track_complaints': 'قدّم شكوى أو تابع حالتها',
  'complaint_description':
      'اشرح المشكلة بوضوح. يمكنك إرسال شكوى عامة أو ربطها بمعمل.',
  'related_lab': 'المعمل المرتبط',
  'optional': 'اختياري',
  'general_complaint': 'شكوى عامة (بدون معمل)',
  'complaint_content': 'محتوى الشكوى',
  'complaint_content_hint': 'اكتب 10 أحرف على الأقل...',
  'complaint_required': 'محتوى الشكوى مطلوب',
  'complaint_too_short': 'يجب أن تكون الشكوى 10 أحرف على الأقل',
  'submit_anonymously': 'إرسال بشكل مجهول',
  'complaint_submitted': 'تم إرسال الشكوى بنجاح',
  'no_complaints_yet': 'لا توجد شكاوى بعد',
  'admin_note': 'ملاحظة الإدارة',
  'new': 'جديدة',
  'in_review': 'قيد المراجعة',
  'resolved': 'تم الحل',
  'dismissed': 'مرفوضة',

  // Grades
  'all_grades': 'كل الدرجات',
  'filter_by_lab': 'تصفية حسب المعمل',

  // Files
  'open_file': 'فتح الملف',
  'file_details': 'تفاصيل الملف',
  'download_and_open': 'تحميل وفتح',
  'downloading': 'جاري التحميل...',
  'view_image': 'عرض الصورة',
  'storage_permission_required': 'إذن التخزين مطلوب لتحميل الملفات',
  'download_failed': 'فشل تحميل الملف',
  'no_app_to_open_file': 'لا يوجد تطبيق لفتح هذا الملف',
  'warning': 'تحذير',
  'lab_not_found': 'معلومات المعمل غير موجودة',

  // Chat
  'chat.title': 'الدردشة',
  'chat.subtitle.lobby': 'دردشة مجتمع المعلمين',
  'chat.empty': 'لا توجد رسائل بعد',
  'chat.empty.subtitle': 'ابدأ المحادثة بإرسال رسالة',
  'chat.error': 'فشل تحميل الرسائل',
  'chat.input.hint': 'اكتب رسالة...',
  'chat.send': 'إرسال',
  'chat.attach.file': 'إرفاق ملف',
  'type_message': 'اكتب رسالة',
  'send': 'إرسال',

  // IP config
  'configure_server_ip': 'إعداد عنوان الخادم',
  'server_configuration': 'إعدادات الخادم',
  'server_configuration_description':
      'سيتم استخدام هذا العنوان لجميع طلبات الـ API واتصالات WebSocket.',
  'server_config_saved': 'تم حفظ إعدادات الخادم بنجاح',
  'ip_segment_1': 'الجزء الأول من IP',
  'ip_segment_2': 'الجزء الثاني من IP',
  'ip_segment_3': 'الجزء الثالث من IP',
  'ip_segment_4': 'الجزء الرابع من IP',
  'port': 'المنفذ',
  'save': 'حفظ',

  // Labs
  'lab_details': 'تفاصيل المعمل',
  'view_sessions': 'عرض الجلسات',
  'teacher': 'المعلم',
  'description': 'الوصف',
  'enroll': 'التسجيل',
  'enrolling': 'جاري التسجيل...',
  'enrollment_success': 'تم التسجيل في المعمل بنجاح',
  'enrollment_error': 'فشل التسجيل في المعمل',
  'enrolled_labs': 'المعامل المسجلة',
  'available_labs': 'المعامل المتاحة',
  'labs': 'المعامل',
  'labs_sessions_subtitle': 'عرض الجلسات المجدولة',
  'labs_grades_subtitle': 'اطّلع على درجاتك',
  'labs_files_subtitle': 'ملفات المعمل المشتركة',
  'labs_chat_subtitle': 'تواصل مع صفك',
  'search_labs_hint': 'ابحث عن المعامل أو المعلمين...',
  'loading_labs': 'جاري تحميل المعامل...',
  'no_labs_found': 'لم يتم العثور على معامل',
  'try_different_search': 'جرّب بحثاً مختلفاً',
  'no_labs_available': 'لا توجد معامل متاحة بعد',
  'loading_sessions': 'جاري تحميل الجلسات...',
  'no_sessions': 'لا توجد جلسات',
  'no_sessions_available': 'لا توجد جلسات متاحة بعد',
  'live': 'مباشر',
  'loading_grades': 'جاري تحميل الدرجات...',
  'no_grades_yet': 'لا توجد درجات بعد',
  'grades_will_appear': 'ستظهر درجاتك هنا',
  'no_grades_found': 'لم يتم العثور على درجات',
  'no_grades_for_category': 'لا توجد درجات لهذه الفئة',
  'all': 'الكل',
  'close': 'إغلاق',

  // Sessions
  'session_details': 'تفاصيل الجلسة',
  'start_time': 'وقت البدء',
  'end_time': 'وقت الانتهاء',
  'streaming': 'بث مباشر',
  'not_streaming': 'لا يوجد بث',
  'recorded_video': 'فيديو مسجل',
  'no_recorded_video': 'لا يوجد فيديو مسجل',

  // Attendance
  'present': 'حاضر',
  'late': 'متأخر',
  'absent': 'غائب',
  'attendance_submitted': 'تم تسجيل الحضور بنجاح',
  'attendance_submit_error': 'فشل تسجيل الحضور',

  // Grades
  'score': 'الدرجة',
  'max_score': 'الدرجة الكاملة',
  'percentage': 'النسبة المئوية',
  'comment': 'تعليق',

  // Files
  'file_name': 'اسم الملف',
  'file_size': 'حجم الملف',
  'created_at': 'تاريخ الإنشاء',
  'no_files': 'لا توجد ملفات',
  'session_recording': 'تسجيل الجلسة',

  // Chat
  'no_messages': 'لا توجد رسائل بعد',
  'chat_history': 'سجل المحادثة',
  'chat_no_lab_selected': 'يرجى اختيار معمل لعرض المحادثة',
  'go_back': 'رجوع',
  'today': 'اليوم',
  'yesterday': 'أمس',
  'unknown': 'غير معروف',
  'invalid_ip': 'يرجى إدخال عنوان IPv4 صحيح',
  'invalid_port': 'يرجى إدخال منفذ صحيح (1-65535)',

  // General / auth status
  'checking_authentication': 'جارٍ التحقق من المصادقة...',

  // Token expiration
  'token_expired': 'انتهت الجلسة',
  'token_refresh_failed': 'فشل تحديث الجلسة. يرجى تسجيل الدخول مرة أخرى.',
  'session_expired_message': 'انتهت جلستك. يرجى تسجيل الدخول مرة أخرى.',
  'refreshing_token': 'جارٍ تحديث الجلسة...',

  // Notification messages
  'enrollment_confirmed': 'تم تأكيد التسجيل',
  'enrollment_confirmed_message': 'تم تسجيلك بنجاح في المعمل.',
  'unenrollment_confirmed': 'تم تأكيد إلغاء التسجيل',
  'unenrollment_confirmed_message': 'لقد تركت المعمل.',
  'session_created': 'تم إنشاء جلسة جديدة',
  'session_created_message': 'تم جدولة جلسة جديدة.',
  'session_started': 'بدأت الجلسة',
  'session_started_message': 'بدأت الجلسة.',
  'session_updated': 'تم تحديث الجلسة',
  'session_updated_message': 'تم تحديث تفاصيل الجلسة.',
  'session_ended': 'انتهت الجلسة',
  'session_ended_message': 'انتهت الجلسة.',
  'new_message': 'رسالة جديدة',
  'new_chat_message': 'رسالة محادثة جديدة.',
};
